"""string

Revision ID: b05922bf5f39
Revises: 2f8eb37dafe1
Create Date: 2022-09-29 15:01:51.873716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05922bf5f39'
down_revision = '2f8eb37dafe1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('register')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('username', name='register_pkey')
    )
    # ### end Alembic commands ###
