"""change to str

Revision ID: 8c26ba7ac5a6
Revises: 85a08b4e9709
Create Date: 2022-09-01 14:56:37.438261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c26ba7ac5a6'
down_revision = '85a08b4e9709'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('general_info', sa.Column('sub_week', sa.Integer(), nullable=True))
    op.add_column('general_info', sa.Column('moral_week', sa.Integer(), nullable=True))
    op.add_column('general_info', sa.Column('year_begin', sa.String(), nullable=True))
    op.add_column('general_info', sa.Column('year_end', sa.String(), nullable=True))
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('staffdetails')
    # op.drop_table('migration')
    # op.drop_table('JWTsam')
    # op.drop_table('academicinfo')
    # op.drop_table('mercy')
    # op.alter_column('log', 'username',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.alter_column('token', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            autoincrement=True)
    # # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('log', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('mercy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mercy_pkey')
    )
    op.create_table('academicinfo',
    sa.Column('school_building', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('built_area', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('play_area', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('no_building', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provision', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('no_staircases', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_lift', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_rooms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srooms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plab', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clab', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blab', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mlab', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comlab', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('llab', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hslab', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('library', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auditorium', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('counroom', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parlor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('proom', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sick_room', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('canteen', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('secroom', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oroom', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stoilet', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('std_toilet', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rooms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spcl_stud', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wall', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('if_wall', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cctv', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ds', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('no_camera', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guard', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('no_guard', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fguard', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('no_fguard', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('water', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('drainage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mmeals', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('no_buses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nola', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_aid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_water', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_sbus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('free_tran', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cam_area', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pas', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('school_building', name='academicinfo_pkey')
    )
    op.create_table('JWTsam',
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_name', name='JWTsam_pkey')
    )
    op.create_table('migration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='migration_pkey')
    )
    op.create_table('staffdetails',
    sa.Column('prin_permale', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prin_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prin_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prin_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prin_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prin_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vp_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vp_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vp_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vp_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vp_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vp_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pg_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pg_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pg_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pg_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pg_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pg_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tg_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tg_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tg_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tg_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tg_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tg_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prt_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prt_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prt_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prt_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prt_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prt_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nt_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nt_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nt_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nt_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nt_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nt_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lib_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lib_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lib_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lib_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lib_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lib_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('art_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('art_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('art_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('art_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('art_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('art_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coun_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coun_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coun_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coun_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coun_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coun_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comlit_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comlit_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comlit_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comlit_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comlit_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comlit_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('faithmin_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('faithmin_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('faithmin_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('faithmin_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('faithmin_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('faithmin_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nurse_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nurse_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nurse_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nurse_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nurse_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nurse_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pt_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pt_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pt_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pt_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pt_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pt_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('om_per', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('om_tem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('om_part', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('om_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oa_per', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oa_tem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oa_part', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oa_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clerk_per', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clerk_tem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clerk_part', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clerk_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lab_per', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lab_tem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lab_part', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lab_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acc_per', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acc_tem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acc_part', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acc_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peon_per', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peon_tem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peon_part', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peon_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_per', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_tem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_part', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ut_permale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ut_perfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ut_temmale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ut_temfemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ut_tomale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ut_tofemale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prin_permale', name='staffdetails_pkey')
    )
    # ### end Alembic commands ###
