
from numbers import Integral
from operator import itemgetter
import string

from sqlalchemy import Column,Integer,String,Boolean,ForeignKey,Time
# from sqlalchemy.sql.expression import null
from .database import Base

class Product(Base):
    __tablename__="product"
    id=Column(Integer,primary_key = True, nullable=False)
    name=Column(String,nullable=True)
    age=Column(Integer)
    gender=Column(String)
    father_name=Column(String)
    mother_name=Column(String)
    

class encrypt(Base):
    __tablename__="pwdencrypt" 
    user_name=Column(String,primary_key=True)
    password=Column(String)


class register(Base):
    __tablename__="register"
    # id=Column(Integer,auto_increment=True)
    name=Column(String,nullable=False,)
    age=Column(Integer,nullable=False,)
    gender=Column(String,nullable=False,)
    father_name=Column(String,nullable=False,)
    mother_name=Column(String,nullable=False,)
    password=Column(String,nullable=False,)
    user_name=Column(String,primary_key=True,nullable=False,)

class general(Base):
    __tablename__='general_info'
    id = Column(Integer,primary_key=True,autoincrement=True)
    user_name=Column(String,ForeignKey("register.user_name",ondelete="CASCADE"))
    sname=Column(String)
    post=Column(String)
    district=Column(String)
    state=Column(String)
    city=Column(String)
    pno=Column(Integer)
    url=Column(String)
    email=Column(String)
    pcode=Column(Integer)
    slocation=Column(String)
    need=Column(String)
    ayear=Column(Integer)
    year=Column(Integer)
    slevel=Column(String)
    medium=Column(String)
    nature=Column(String)
    tstaff=Column(Integer)
    gender=Column(String)
    girls=Column(Integer)
    boys=Column(Integer)
    students=Column(Integer)
    nstaff=Column(Integer)
    cname=Column(String)
    cpno=Column(Integer)
    pname=Column(String)
    pemail=Column(String)
    ppno=Column(Integer)
    opno=Column(Integer)
    institute_govt=Column(String)
    board_affiliated=Column(String)
    affiliation_no=Column(Integer)
    affiliation_year=Column(Integer)
    affiliation_condition=Column(String)
    affiliation_cons=Column(Integer)
    status_certificate=Column(String)
    hindhu=Column(Integer)
    cristian=Column(Integer)
    islam=Column(Integer)
    others=Column(Integer)
    non_believers=Column(Integer)
    fire_certificate=Column(String)
    sanitation_certificate=Column(String)
    building_certificate=Column(String)
    school_owned=Column(String)
    name_trust=Column(String)
    registered=Column(String)
    under_act=Column(String)
    registration_year=Column(Integer)
    registration_no=Column(Integer)
    period_validity=Column(Integer)
    name_chairman=Column(String)
    designation=Column(String)
    address_chairman=Column(String)
    pno_chairman=Column(String)
    email_chairman=Column(String)
    governing=Column(String)
    members=Column(Integer)
    tenure=Column(Integer)
    epcc=Column(String)
    members_epcc=Column(Integer)
    epcc_tenure=Column(Integer)
    pt_executive=Column(String)
    pt_members=Column(Integer)
    pt_tenure=Column(Integer)
    st_councill=Column(String)
    st_members=Column(Integer)
    st_tenure=Column(Integer)
    general_grievance=Column(String)
    sm_committee=Column(String)
    cm_committee=Column(String)
    cm_members=Column(Integer)
    cm_tenure=Column(Integer)
    school_building=Column(String)
    built_area=Column(String)
    play_area=Column(String)
    no_building=Column(Integer)
    provision=Column(String)
    no_staircases=Column(Integer)
    no_lift=Column(Integer)
    class_rooms=Column(Integer)
    srooms=Column(Integer)
    plab=Column(Integer)
    clab=Column(Integer)
    blab=Column(Integer)
    mlab=Column(Integer)
    comlab=Column(Integer)
    llab=Column(Integer)
    hslab=Column(Integer)
    library=Column(Integer)
    auditorium=Column(Integer)
    counroom=Column(Integer)
    parlor=Column(Integer)
    proom=Column(Integer)
    sick_room=Column(Integer)
    canteen=Column(Integer)
    secroom=Column(Integer)
    oroom=Column(Integer)
    stoilet=Column(Integer)
    std_toilet=Column(Integer)
    rooms=Column(Integer)
    spcl_stud=Column(String)
    wall=Column(String)
    if_wall=Column(String)
    cctv=Column(String)
    ds=Column(String)
    no_camera=Column(Integer)
    guard=Column(String)
    no_guard=Column(Integer)
    fguard=Column(String)
    no_fguard=Column(Integer)
    water=Column(String)
    drainage=Column(String)
    mmeals=Column(String)
    no_buses=Column(Integer)
    gps=Column(Integer)
    nola=Column(Integer)
    first_aid=Column(Integer)
    no_water=Column(Integer)
    no_sbus=Column(Integer)
    free_tran=Column(String)
    cam_area=Column(String)
    pas=Column(String)
    prin_permale=Column(Integer)
    prin_perfemale=Column(Integer)
    prin_temmale=Column(Integer)
    prin_temfemale=Column(Integer)
    
    vp_permale=Column(Integer)
    vp_perfemale=Column(Integer)
    vp_temmale=Column(Integer)
    vp_temfemale=Column(Integer)
   
    pg_permale=Column(Integer)
    pg_perfemale=Column(Integer)
    pg_temmale=Column(Integer)
    pg_temfemale=Column(Integer)
  
    tg_permale=Column(Integer)
    tg_perfemale=Column(Integer)
    tg_temmale=Column(Integer)
    tg_temfemale=Column(Integer)
   
    prt_permale=Column(Integer)
    prt_perfemale=Column(Integer)
    prt_temmale=Column(Integer)
    prt_temfemale=Column(Integer)
   
    nt_permale=Column(Integer)
    nt_perfemale=Column(Integer)
    nt_temmale=Column(Integer)
    nt_temfemale=Column(Integer)
   
    lib_permale=Column(Integer)
    lib_perfemale=Column(Integer)
    lib_temmale=Column(Integer)
    lib_temfemale=Column(Integer)
    
    art_permale=Column(Integer)
    art_perfemale=Column(Integer)
    art_temmale=Column(Integer)
    art_temfemale=Column(Integer)
 
    coun_permale=Column(Integer)
    coun_perfemale=Column(Integer)
    coun_temmale=Column(Integer)
    coun_temfemale=Column(Integer)
    
  
    comlit_permale=Column(Integer)
    comlit_perfemale=Column(Integer)
    comlit_temmale=Column(Integer)
    comlit_temfemale=Column(Integer)
    
    faithmin_permale=Column(Integer)
    faithmin_perfemale=Column(Integer)
    faithmin_temmale=Column(Integer)
    faithmin_temfemale=Column(Integer)
 
    nurse_permale=Column(Integer)
    nurse_perfemale=Column(Integer)
    nurse_temmale=Column(Integer)
    nurse_temfemale=Column(Integer)

    pt_permale=Column(Integer)
    pt_perfemale=Column(Integer)
    pt_temmale=Column(Integer)
    pt_temfemale=Column(Integer)

  
   
    om_per=Column(Integer)
    om_tem=Column(Integer)
    om_part=Column(Integer)
  
    oa_per=Column(Integer)
    oa_tem=Column(Integer)
    oa_part=Column(Integer)
    # oa_total=Column(Integer)
    clerk_per=Column(Integer)
    clerk_tem=Column(Integer)
    clerk_part=Column(Integer)
  
    lab_per=Column(Integer)
    lab_tem=Column(Integer)
    lab_part=Column(Integer)
 
    acc_per=Column(Integer)
    acc_tem=Column(Integer)
    acc_part=Column(Integer)
 
    peon_per=Column(Integer)
    peon_tem=Column(Integer)
    peon_part=Column(Integer)
    
    other_per=Column(Integer)
    other_tem=Column(Integer)
    other_part=Column(Integer)
    
    ut_permale=Column(Integer)
    ut_perfemale=Column(Integer)
    ut_temmale=Column(Integer)
    ut_temfemale=Column(Integer)

    no_curricular_carried=Column(Integer)
    no_groups=Column(Integer)
    no_community=Column(Integer)

    last_school=Column(Integer)
    last_zonal=Column(Integer)
    last_district=Column(Integer)
    last_state=Column(Integer)
    last_national=Column(Integer)
    last_international=Column(Integer)

    com_school=Column(Integer)
    com_zonal=Column(Integer)
    com_district=Column(Integer)
    com_state=Column(Integer)
    com_national=Column(Integer)
    com_international=Column(Integer)

    sclpro_school=Column(Integer)
    sclpro_zonal=Column(Integer)
    sclpro_district=Column(Integer)
    sclpro_state=Column(Integer)
    sclpro_national=Column(Integer)
    sclpro_international=Column(Integer)

    year_begin=Column(String)
    year_end=Column(String)
    workday_21_22=Column(Integer)
    workday_20_21=Column(Integer)
    workday_19_20=Column(Integer)
    hours_21_22=Column(Integer)
    hours_20_21=Column(Integer)
    hours_19_20=Column(Integer)
    instructional_hours_21_22=Column(Integer)
    instructional_hours_20_21=Column(Integer)
    instructional_hours_19_20=Column(Integer)
    non_instructional_hours_21_22=Column(Integer)
    non_instructional_hours_20_21=Column(Integer)
    non_instructional_hours_19_20=Column(Integer)
    holidays_21_22=Column(Integer)
    holidays_20_21=Column(Integer)
    holidays_19_20=Column(Integer)

    sub_week=Column(Integer)
    moral_week=Column(Integer)
    duration_teaching=Column(Integer)
    no_clubs=Column(Integer)
    summer_from=Column(Time)
    summer_to=Column(Time)
    winter_from=Column(Time)
    winter_to=Column(Time)
    shifts=Column(Time)


  


class post(Base):
    __tablename__="token"
    title=Column(String,primary_key=True)
    content=Column(String)
    id=Column(Integer,autoincrement=True,nullable=False)

class login(Base):
    __tablename__="log" 
    username=Column(String,nullable=True,primary_key=True)
    password=Column(String,nullable=True)
